ARG NODE_VERSION=20.18.0
FROM node:${NODE_VERSION}-alpine as base
ENV NODE_ENV=development
WORKDIR /app

FROM base as build
COPY package*.json ./
RUN npm install

FROM base
COPY --from=build /app/node_modules /app/node_modules
EXPOSE 3000
CMD [ "npm", "run", "dev" ]