version: "3.8"
services:
  ui:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3000
      - 24678:24678
    environment:
      HOST: 0.0.0.0
    restart: always
    volumes:
      - ./:/app
    networks:
      - nuxt-services-net

networks:
  nuxt-services-net:
    name: nuxt-services-net


